# Generated by Django 4.1.5 on 2023-09-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=25)),
            ],
        ),
    ]
