# Generated by Django 4.1.5 on 2023-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnm', models.CharField(max_length=25)),
                ('fimg', models.FileField(upload_to='Images')),
                ('fpr', models.IntegerField()),
            ],
        ),
    ]
